language: scala
scala:
   - 2.10.6
jdk:
   - openjdk6
env:
  - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"
script:
  - sbt ++$TRAVIS_SCALA_VERSION --warn update compile scripted

sudo: false

addons:
  apt:
    packages:
    - nodejs

install:
  - gem install jekyll --no-rdoc --no-ri
  - gem list jekyll
