language: scala
scala:
   - 2.10.6
jdk:
   - openjdk7

script:
  - sbt ++$TRAVIS_SCALA_VERSION --warn update compile scripted

sudo: false

addons:
  apt:
    packages:
    - nodejs
    - python-sphinx

before_install:
  - rvm install 2.2.3

install:
  - gem install jekyll:2.5.3 nanoc:3.8.0 asciidoctor --no-rdoc --no-ri
  - npm install -g gitbook-cli
  - |
    mkdir $TRAVIS_BUILD_DIR/download && mkdir $HOME/bin && \
    wget https://github.com/spf13/hugo/releases/download/v0.16/hugo_0.16_linux-64bit.tgz -O $TRAVIS_BUILD_DIR/download/hugo.tgz && \
    tar xvf $TRAVIS_BUILD_DIR/download/hugo.tgz && \
    mv $TRAVIS_BUILD_DIR/hugo $HOME/bin/hugo && \
    chmod +x $HOME/bin/hugo && \
    rm -rf $TRAVIS_BUILD_DIR/download/

before_script:
  - export PATH=$PATH:$HOME/bin/
